### ISSUE TITLE
FEATURE: Accessibility Guidelines

### ISSUE THREAD

**Issue by iamjessklein** [wikimedia/WikimediaUI-Style-Guide#134] opened 2018-07-20 01:59 UTC
**Story:** As a UX designer, I want to clearly understand how to practically implement “accessible” visual design.

**Possible solutions:** while this is called out specifically in the [this is for everyone](
https://design.wikimedia.org/style-guide/design-principles.html#this-is-for-everyone) principle, it might be worth connecting some actionable bullets to this or dedicating a new in-depth chapter(s) towards accessibility and localization.

**Opportunity:** right now this content is sprinkled throughout the guide, however, if it was consolidated it would provide creators with a chance to deep dive into complex questions around localization, screen readers, meta data etc

**Comment by Volker-E** [comment] 2019-02-06 08:36
We've been integrating accessibility requirements and measurements in various section of current style guide. 
Such a “connecting the dots” section could provide an overview of 
- why it's important to care about accessbility, 
- types of disabilities covered and 
- what measurements we are taking on to provide “accessibility by design“:
-- Color palette and use of color
-- Semantic HTML and SVG markup (enriched by following ARIA best practices and adding roles and attributes)
-- Text alternatives for images, illustrations, icons and graphs (MathML?)
-- Keyboard and tactile interfaces ready
-- Resources with external links

Such a page has to be seen (and probably rolled out) in context of #32 and #146

**Comment by Volker-E** [comment] 2020-03-11 22:01
Successfully resolved with above! 🎉

**Closed by Volker-E** 2020-03-11 22:01 UTC
Labels: feature
